maurogram/urls.py
"""Maurogram URLs module."""

# Django
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import logout
from django.urls import path, include

from maurogram import views as local_views
from users import views as users_views


urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include(('posts.urls','posts'),namespace='posts')),
    path('users/', include(('users.urls','users'),namespace='users')),
    # path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [
    

    path(
        route = '', 
        view = views.PostFeedView.as_view(), 
        name='home',
        kwargs = {'type':'follow'}
    ), 

    path(
        route = 'posts/', 
        view = views.PostFeedView.as_view(), 
        name='feed',
        kwargs = {'type':'follow'}
    ),

    path(
        route = 'posts/all/', 
        view = views.PostFeedView.as_view(), 
        name='all',
        kwargs = {'type':'all'}
    ),

    path(
        route = 'posts/new/', 
        view = views.CreatePostView.as_view(), 
        name='create'
    ),

    path(
        route='post/<str:username>/<int:id>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),
    
    path(
        route='comment/<str:username>/<int:id>/',
        view = views.comment,
        name='new_commentary'
    ),
    path(
        route='like/<str:username>/<int:id>/',
        view = views.like,
        name='like'
    ),
    
]

posts/models.py
"""Posts models."""

#Django
from django.db import models
from users.models import User
import uuid


def upload_location(instance, filename):
    base = 'posts/photos/'
    username = instance.user.username
    extension = filename.split(".")[-1]
    return base + "%s/%s.%s" %(username,uuid.uuid4(),extension)


class Post(models.Model):
    """Post model."""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    #profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    profile = models.ForeignKey('users.Profile', on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    photo = models.ImageField(upload_to=upload_location)

    created  = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return title and username."""
        return  f'{self.title} by @{self.user.username}'
    

class Like(models.Model):
    """Follow model.""" 
    profile = models.ForeignKey(User,   on_delete=models.SET_NULL, null=True)
    post    = models.ForeignKey('Post', on_delete=models.SET_NULL, null=True)
    # post = models.IntegerField(blank=True)

    LOAN_STATUS = (
        ('l', 'like'),
        ('n', 'not like'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='n')

    created  = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)  


class Comment(models.Model):
    """Comments model """
    user = models.ForeignKey(User, on_delete=models.RESTRICT)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    comment = models.CharField(max_length=250, blank=True)

    LOAN_STATUS = (
        ('a', 'active'),
        ('n', 'not active'),
        ('d', 'delete'),
        ('b', 'banned'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='a')

    created  = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

posts/forms.py
"""Post forms."""

# Django
from django import forms

# Models
from posts.models import Post


class PostForm(forms.ModelForm):
    """Post model form."""

    class Meta:
        """Form settings."""

        model = Post
        fields = ('user', 'profile', 'title', 'photo')

posts/views.py
"""Posts views."""
#Django
from django.db.models.expressions import RawSQL
from django.http import request
from users.models import Follow
from django.urls import reverse_lazy
from django.contrib.auth.mixins  import LoginRequiredMixin #investigar mixin
from django.views.generic import ListView, DetailView, CreateView #investigar
from django.shortcuts import redirect, render
from django.template.defaulttags import register
from django.db import connections
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

# Forms
from posts.forms import PostForm

# Models
from posts.models import Post, Like, Comment


class PostFeedView(LoginRequiredMixin, ListView):
    """Return follow's published posts."""
    
    template_name = 'posts/feed.html'
    model = Post
    ordering = ('-created',)
    paginate_by = 2
    context_object_name = 'posts'


    def get_queryset(self):
        level = self.kwargs['type']
        if level == 'all':
            queryset = Post.objects.raw('SELECT p.* FROM posts_post as p, users_follow as f WHERE f.profile_id = ' + str(self.request.user.id) + ' AND f.user = p.user_id ORDER BY p.id DESC ')
        else:
            queryset = Post.objects.all().order_by('-created')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['limit_comment'] = 2
        return context
        # page_number = self.request.GET.get('page')
        # print(str(self.paginate_by)+" and "+str(page_number))



class PostDetailView(LoginRequiredMixin, DetailView):
    """Posts detail view."""

    template_name = 'posts/detail.html'
    slug_field = 'id'
    slug_url_kwarg = 'id'
    queryset = Post.objects.all()
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['limit_comment'] = 0
        return context
   

class CreatePostView(LoginRequiredMixin, CreateView):
    """Create a new post."""

    template_name = 'posts/new.html'
    form_class = PostForm
    success_url = reverse_lazy('posts:feed')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user']    = self.request.user
        context['profile'] = self.request.user.profile
        return context

@login_required
def like(request, username, id):
    """Like post."""
    
    profile= request.user
    post = Post.objects.filter(id=id).first()
    instance  = Like.objects.filter(profile=profile,post=post).first()

    # Search if Like instace exist or make a new one
    if instance:
        like = instance
    else:
        like = Like()

    like.post= post
    like.profile = profile

    # Set status of Like instance
    if instance:
        if instance.status == 'n':
            like.status = 'l'
        else:
            like.status = 'n'
    else:
        like.status = 'l'

    like.save()
    return redirect("posts:detail", username=username, id=id)

@login_required
def comment(request, username, id):
    """Like post."""
    
    profile= request.user
    post = Post.objects.filter(id=id).first()
    
    comment = Comment()

    comment.comment = request.POST['commentary']
    comment.status  = 'a'
    comment.post = post
    comment.user = profile
    comment.save()

    return redirect("posts:detail", username=username, id=id)

@register.filter
def get_value(dictionary, key):
    """Return a value from dict"""
    return dictionary[key]

@register.filter
def get_likes(post):
    return Like.objects.filter(post=post, status= 'l').count()

@register.filter
def get_own_like(post, profile):
    val = Like.objects.values('status').filter(post=post, status= 'l', profile=profile).first()
    return val['status']

@register.filter
def get_comments(post,limit_comment):
    select_c = "SELECT c.id, c.comment, c.status, c.created, u.username as username, p.picture as picture, u.first_name, u.last_name "
    form_c   = "FROM posts_comment as c, users_user as u, users_profile as p "
    where_c  = "WHERE c.status LIKE 'a' AND c.user_id = u.id AND p.user_id = u.id "
    limit_text = ""
    if limit_comment > 0:
        limit_text = "LIMIT "+ str(limit_comment)
    comments = Comment.objects.raw(select_c + form_c + where_c + ' AND c.post_id = '+str(post.id)+' ORDER BY c.id DESC '+limit_text) 
    return comments

@register.filter
def get_count_all_comments(post, descount):
    if descount > 0:
        post_count_comment = Comment.objects.filter(post=post, status='a').count()-descount
        return post_count_comment
    else:
        return 0

templates/posts/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>
    @{{user.username}} | Maurogram
</title>
{% endblock %}

{% block container %}
    <div class="container" >
        <div class="row">
            {% include "posts/post_card.html" %}
        </div>
    </div>

{% endblock %}

templates/posts/feed.html
{% extends "base.html" %}

{% block head_content %}
    <title>Maurogram</title>
{% endblock%}

{% block container %}
    <div class="container">
        <div class="row">

            {% for post in posts %}
                {% include "posts/post_card.html" %}
            {% endfor %}
            
        </div>
    </div>

    {% include "pagination.html" %}

{% endblock %}

templates/posts/new.html
{% extends "base.html" %}

{% block head_content %}
<title>Nuevo post</title>
{% endblock %}

{% block container %}

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6 pt-3 pb-3" id="profile-box">
                <h4 class="mb-4">Nueva foto</h4>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <input type="hidden" name="user" value="{{ user.pk}}" />
                    <input type="hidden" name="profile" value="{{ profile.pk }}" />

                    {# Website field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.title.errors %}is-invalid{% endif %}"
                            type="text"
                            name="title"
                            placeholder="Título"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# Photo field #}
                    <div class="form-group">
                        <label>Elige tu foto:</label>
                        <input
                            class="form-control {% if form.photo.errors %}is-invalid{% endif %}"
                            type="file"
                            name="photo"
                            placeholder="Foto"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.photo.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block mt-5">Publicar</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/posts/post_card.html
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
    <div class="media pt-3 pl-3 pb-1">
        <a href="{% url "users:detail" post.user.username %}">
            <img class="mr-3 rounded-circle" height="35" src="{{ post.profile.picture.url }}" alt="{{ post.user.get_full_name }}">
        </a>
        <div class="media-body">
            <p style="margin-top: 5px;">{{ post.user.get_full_name  }}</p>
        </div>
    </div>

    <a href="{% url "posts:detail" user.username post.id %}" >
        <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.title }}">
    </a>

    <p class="mt-1 ml-2" >
        <a href="{% url "posts:like" user.username post.id %}" style="color: #000; font-size: 20px;">
            {% if post.id|get_own_like:user  == 'l' %}
                <i class="fas fa-heart"></i>
            {% else %}
                <i class="far fa-heart"></i>
            {% endif %} </a>
            {{ post.id|get_likes }} likes 
    </p>

    <p class="ml-2 mt-0 mb-2">
        <b>{{ post.title }}</b> - <small>{{ post.created }}</small>
    </p>

    {% for comment in post|get_comments:limit_comment %}
        {% if forloop.counter0 == 0 %}
        <hr>
        {% endif %}        
        <div class="media pt-3 pl-3 pb-2">
            <a href="{% url "users:detail" comment.username %}">
                <img class="mr-3 rounded-circle" height="40" src="/media/{{ comment.picture }}" alt="{{ comment.username }}">
            </a>
            <div class="media-body">
                <p><b>{{comment.first_name}} {{comment.last_name}}</b> {{ comment.comment }}</p>
            </div>
        </div>
    {% endfor %}

    <div class="container">
        <div class="row" >
            <div class="col"></div>
            <div class="col"></div>
            <div class="col text-right text-info">
                {% with count_comment=post|get_count_all_comments:limit_comment %}
                    {% if count_comment > 0 %}
                        <p >
                        <a class="text-info" href="{% url "posts:detail" post.user.username post.id %}">
                        {{count_comment}}
                        {% if count_comment == 1 %}comentario más{% else %}comentarios más{% endif %}
                        </a>
                        </p>
                    {% endif %}
                {% endwith %}
            </div>
        </div>
    </div>

    <form action="{% url "posts:new_commentary" post.user.username post.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="input-group">
            <input 
                type="text" 
                class="form-control" 
                placeholder="Añade un comentario"
                name="commentary"
            >
            <button 
                type="submit" 
                class="btn btn-outline-secondary"
            >Publicar</button>
        </div>
    </form>
    
</div>