maurogram/urls.py
"""Maurogram URLs module."""

# Django
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import logout
from django.urls import path, include

from maurogram import views as local_views
from users import views as users_views


urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include(('posts.urls','posts'),namespace='posts')),
    path('users/', include(('users.urls','users'),namespace='users')),
    # path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [
    

    path(
        route = '', 
        view = views.PostFeedView.as_view(), 
        name='home',
        kwargs = {'type':'follow'}
    ), 

    path(
        route = 'posts/', 
        view = views.PostFeedView.as_view(), 
        name='feed',
        kwargs = {'type':'follow'}
    ),

    path(
        route = 'posts/all/', 
        view = views.PostFeedView.as_view(), 
        name='all',
        kwargs = {'type':'all'}
    ),

    path(
        route = 'posts/new/', 
        view = views.CreatePostView.as_view(), 
        name='create'
    ),

    path(
        route='post/<str:username>/<int:id>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),
    
    path(
        route='comment/<str:username>/<int:id>/',
        view = views.comment,
        name='new_commentary'
    ),
    path(
        route='like/<str:username>/<int:id>/',
        view = views.like,
        name='like'
    ),
    
]

users/urls.py
"""User URLs"""

# Django
from django.urls import path
from django.views.generic import TemplateView
# from django.views.generic import TemplateView

# Views
from users import views

urlpatterns = [

    # Management
    path(
        route = 'login/',
        view = views.LoginView.as_view(),
        name='login'
    ),

    path(
        route = 'logout/',    
        view = views.LogoutView.as_view(),
        name='logout'
    ),

    path(
        route = 'signup/',    
        view = views.SignupView.as_view(),
        name='signup'
    ),

    path(
        route = 'me/profile/', 
        view = views.UpdateProfileView.as_view(),
        name='update_profile'
    ),
    path(
        route='follow/<str:username>/',
        view = views.follow,
        name='follow'
    ),

    path(
        route = 'reset_password/', 
        view = views.ResetPasswordView.as_view(),
        # view = views.func,
        name='reset_password'
    ),

    path(
        route = 'change_password/<str:token>', 
        view = views.ChangePasswordView.as_view(),
        name='change_password'
    ),

    path(
        route='search/',
        view = views.search_user,
        name='search'
    ),

    # Posts
    path(
        route='profile/<str:username>/',
        # view = TemplateView.as_view(template_name='users/detail.html'),
        view = views.UserDetailView.as_view(),
        name='detail'
    ),

    


    

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body>
    {% include "nav.html" %}
    
    <div class="container mt-5">
        {% block container %}
        {% endblock %}
    </div>
</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url "posts:feed" %}">
            <img src="{% static "img/instagram.png" %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href="{% url "users:detail" request.user.username %}">
                        {% if request.user.profile.picture %}
                            <img src="{{ request.user.profile.picture.url }}" class="rounded-circle" height="35"/>
                        {% else %}
                           <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="35"/>
                        {% endif %}
                    </a>

                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url "posts:create" %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url "users:logout" %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url "posts:all" %}">
                        <i class="fas fa-globe"></i>
                    </a>
                </li>

            </ul>

            <form class="d-flex" method="POST" action="{% url "users:search"%}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="input-group">
                    <span class="input-group-text" id="basic-addon1">@</span>
                    <input type="text" class="form-control" name="username" placeholder="Nombre de usuario">
                    <button class="btn btn-outline-secondary" type="submit">Ir</button>
                </div>
            </form>

        </div>
    </div>
</nav>

templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Atrás
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Siguiente
            </a>
        </li>
        {% endif %}
    </ul>
</nav>