maurogram/urls.py
"""Maurogram URLs module."""

# Django
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import logout
from django.urls import path, include

from maurogram import views as local_views
from users import views as users_views


urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include(('posts.urls','posts'),namespace='posts')),
    path('users/', include(('users.urls','users'),namespace='users')),
    # path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [
    

    path(
        route = '', 
        view = views.PostFeedView.as_view(), 
        name='home',
        kwargs = {'type':'follow'}
    ), 

    path(
        route = 'posts/', 
        view = views.PostFeedView.as_view(), 
        name='feed',
        kwargs = {'type':'follow'}
    ),

    path(
        route = 'posts/all/', 
        view = views.PostFeedView.as_view(), 
        name='all',
        kwargs = {'type':'all'}
    ),

    path(
        route = 'posts/new/', 
        view = views.CreatePostView.as_view(), 
        name='create'
    ),

    path(
        route='post/<str:username>/<int:id>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),
    
    path(
        route='comment/<str:username>/<int:id>/',
        view = views.comment,
        name='new_commentary'
    ),
    path(
        route='like/<str:username>/<int:id>/',
        view = views.like,
        name='like'
    ),
    
]

users/urls.py
"""User URLs"""

# Django
from django.urls import path
from django.views.generic import TemplateView
# from django.views.generic import TemplateView

# Views
from users import views

urlpatterns = [

    # Management
    path(
        route = 'login/',
        view = views.LoginView.as_view(),
        name='login'
    ),

    path(
        route = 'logout/',    
        view = views.LogoutView.as_view(),
        name='logout'
    ),

    path(
        route = 'signup/',    
        view = views.SignupView.as_view(),
        name='signup'
    ),

    path(
        route = 'me/profile/', 
        view = views.UpdateProfileView.as_view(),
        name='update_profile'
    ),
    path(
        route='follow/<str:username>/',
        view = views.follow,
        name='follow'
    ),

    path(
        route = 'reset_password/', 
        view = views.ResetPasswordView.as_view(),
        # view = views.func,
        name='reset_password'
    ),

    path(
        route = 'change_password/<str:token>', 
        view = views.ChangePasswordView.as_view(),
        name='change_password'
    ),

    path(
        route='search/',
        view = views.search_user,
        name='search'
    ),

    # Posts
    path(
        route='profile/<str:username>/',
        # view = TemplateView.as_view(template_name='users/detail.html'),
        view = views.UserDetailView.as_view(),
        name='detail'
    ),

    


    

]

users/forms.py
"""User forms."""

# Django
from django import forms

# Models
from users.models import Profile, User

class SignupForm(forms.Form):
    """Sign up form."""
    username = forms.CharField(
        min_length=4,
        max_length=50,
        label=False,
        widget = forms.TextInput(attrs={'placeholder':'Nombre de usuario','class': 'form-control','required': True})
        )

    password = forms.CharField(
        max_length=70,
        label=False,
        widget = forms.PasswordInput(attrs={'placeholder':'Contraseña','class': 'form-control','required': True})
    )

    password_confirmation = forms.CharField(
        min_length=4,
        max_length=70, 
        label=False,
        widget = forms.PasswordInput(attrs={'placeholder':'Confirme contraseña','class': 'form-control','required': True})
    )
    
    first_name = forms.CharField(
        min_length=2,
        max_length=50,
        label=False,
        widget = forms.TextInput(attrs={'placeholder':'Primer nombre','class': 'form-control','required': True})
        )

    last_name  = forms.CharField(
        min_length=2,
        max_length=50,
        label=False,
        widget = forms.TextInput(attrs={'placeholder':'Apellido','class': 'form-control','required': True})     
        )

    email = forms.CharField(
        min_length=6, 
        max_length=70,
        label=False,
        widget = forms.EmailInput(attrs={'placeholder':'Correo electónico','class': 'form-control','required': True}),
    )

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('El nombre se usuario ya está en uso. ☹')
        return username

    def clean_email(self):
        """Email must be unique."""
        email = self.cleaned_data['email']
        email_taken = User.objects.filter(email=email).exists()
        if email_taken:
            raise forms.ValidationError('Ya existe un usuario con ese correo electrónico.')
        return email

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Las contraseñas no coinciden.')

        return data

    def save(self):
        """Create user and profile"""
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()
        

class ResetPasswordForm(forms.Form):
    username = forms.CharField(
        min_length=4,
        max_length=50,
        label=False,
        widget = forms.TextInput(attrs={'placeholder':'Nombre de usuario','class': 'form-control','required': True, 'autocomplete': 'off'})
    )

    def clean(self):
        data = super().clean()
        if not User.objects.filter(username=data['username']).exists():
            raise forms.ValidationError('El usuario no existe.')
        return data

    def get_user(self):
        username = self.cleaned_data.get('username')
        return User.objects.get(username=username)


class ChangePasswordForm(forms.Form):
    password = forms.CharField(
        min_length=4,
        max_length=50,
        label=False,
        widget = forms.PasswordInput(attrs={'placeholder':'Nueva contraseña','class': 'form-control','required': True, 'autocomplete': 'off'})
    )

    password_confirmation = forms.CharField(
        min_length=4,
        max_length=50,
        label=False,
        widget = forms.PasswordInput(attrs={'placeholder':'Confirmar contraseña','class': 'form-control','required': True, 'autocomplete': 'off'})
    )

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Las contraseñas no coinciden.')

        return data

    def get_user(self,token):
        return User.objects.get(token=token)

users/views.py
"""Users views."""

# Django
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import views as auth_view
from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, FormView
from django.contrib.auth.mixins  import LoginRequiredMixin
from django.views.generic.edit import UpdateView
from django.http import HttpResponseRedirect
from django.template.loader import render_to_string
from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site


#from django.contrib.auth.forms import AuthenticationForm

# Models
from users.models import Profile, User
from posts.models import Post
from users.models import Follow

# Forms
from users.forms import  SignupForm, ResetPasswordForm, ChangePasswordForm

# Utilities
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from maurogram import settings
import uuid


class LoginView(auth_view.LoginView):
    """Login view."""
    template_name = 'users/login.html'

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse('posts:feed'))
        return self.render_to_response(self.get_context_data())


class UserDetailView(LoginRequiredMixin, DetailView): #importante
    """User detail view."""
    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username' #se basa en el nombre de <str:username> que se encuentra en users/urls.py
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add users's posts to context."""
        context = super().get_context_data(**kwargs)
        user = self.get_object()

        context['posts']     = Post.objects.filter(user=user).order_by('-created')
        context['follow']    = Follow.objects.filter(profile=self.request.user.id , user=user.id).first()
        context['followers'] = Follow.objects.filter(user=user.id, status='f').count()
        context['following'] = Follow.objects.filter(profile=user.id, status='f').count()
        context['my_posts']  = Post.objects.filter(user=user).count

        return context


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """Update profile view."""

    template_name = 'users/update_profile.html'
    model = Profile
    fields = ['website', 'biography', 'phone_number', 'picture']

    def get_object(self):
        """Return user's profile"""
        return self.request.user.profile

    def get_success_url(self):
        """Return user's profile."""
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username':username})


class SignupView(FormView):
    """Users sign up view."""

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse('posts:feed'))
        return self.render_to_response(self.get_context_data())

    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('posts:home')

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        username = self.request.POST['username']
        password = self.request.POST['password']
        user = authenticate(self.request, username=username, password=password)
        login(self.request, user)
        return str(self.success_url)


class LogoutView(LoginRequiredMixin, auth_view.LogoutView):
    """Logout view."""
    template_name = 'users/login.html'

    
def follow(request, username):
    """Follow user."""
    
    profile_follow = User.objects.filter(username=username).first()
    profile= request.user
    user=profile_follow.id

    account  = Follow.objects.filter(profile=profile,user=user).first()

    if account:
        follow = account
        if account.status == 'n':
            follow.status = 'f'
        else:
            follow.status = 'n'
    else:
        follow = Follow()
        follow.status = 'f'


    follow.user= user
    follow.profile = profile

    follow.save()

    return redirect("users:detail", username=username)


class ResetPasswordView2(FormView):
    """Reset password view."""

    template_name = 'accounts/resetpwd.html'
    form_class = ResetPasswordForm
    success_url = reverse_lazy('posts:home')

    def sent_email(self, user):
        context = {
            'user': user,
            'link_resetpwd': '',
            'link_home': ''
        }
    
        template = get_template('accounts/send_email.html')
        content = template.render(context)
        

        email = EmailMultiAlternatives(
            'Reseteo de contraseña - Maurogram', #title
            'Maurogram', #Asunto
            settings.EMAIL_HOST_USER, #Quien envía
            [user.email]
        )

        email.attach_alternative(content, 'text/html')
        email.send()

    def form_valid(self, form):
        """."""
        pass
        return super().form_valid(form)

    def post(self, request, *arg, **kwargs):
        data = {}
        try:
            form  = ResetPasswordForm(request.POST) # or self.get_form()
            if form.is_valid():
                user = form.get_user()
                data = self.sent_email(user)
            else:
                data['error'] = form.errors
                
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)
        #return self.form_valid(form)


class ResetPasswordView(FormView):
    """Reset password view."""

    template_name = 'accounts/resetpwd.html'
    form_class = ResetPasswordForm

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse('posts:feed'))
        return self.render_to_response(self.get_context_data())
    
    def send_email_reset_pwd(self, user):
        data = {}
        try:
            URL = settings.DOMAIN if not settings.DEBUG else self.request.META['HTTP_HOST']
            user.token = uuid.uuid4()
            user.save()

            mailServer = smtplib.SMTP(settings.EMAIL_HOST, settings.EMAIL_PORT)
            mailServer.starttls()
            mailServer.login(settings.EMAIL_HOST_USER, settings.EMAIL_HOST_PASSWORD)

            email_to = user.email
            mensaje = MIMEMultipart()
            mensaje['From'] = settings.EMAIL_HOST_USER
            mensaje['To'] = email_to
            mensaje['Subject'] = 'Reseteo de contraseña - Maurogram'

            content = render_to_string('accounts/send_email.html', {
                'user': user,
                'link_resetpwd': f'http://{URL}/users/change_password/{str(user.token)}',
                'link_home': f'http://{URL}',
            })
            mensaje.attach(MIMEText(content, 'html'))

            mailServer.sendmail(settings.EMAIL_HOST_USER,
                                email_to, 
                                mensaje.as_string())
        except Exception as e:
            data['error'] = str(e)
        return data


    def post(self, request, *arg, **kwargs):
        data = {}
        try:
            form  = ResetPasswordForm(request.POST) # or self.get_form()
            if form.is_valid():
                user = form.get_user()
                data = self.send_email_reset_pwd(user) #Para enviar mail
                mail = User.objects.values('email').filter(username=user.username).first()
                return render(request, 'accounts/mail_sended.html', {'mail':mail})
            else:
                data['error'] = form.errors
                
        except Exception as e:
            data['error'] = str(e)
        return self.form_invalid(form)


class ChangePasswordView(FormView):
    """Change password view."""

    template_name = 'accounts/changepwd.html'
    form_class = ChangePasswordForm
    success_url = reverse_lazy('posts:home')

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse('posts:feed'))
        token = self.kwargs['token']
        if User.objects.filter(token=token).exists():
            return super().get(request, *args, **kwargs)
        return HttpResponseRedirect('/')

    def form_valid(self, form):
        """Save form data."""
        return super().form_valid(form)
        

    def post(self, request, *arg, **kwargs):
        data = {}
        try:
            form  = ChangePasswordForm(request.POST) # or self.get_form()
            if form.is_valid():
                user = form.get_user(self.kwargs['token'])
                user.set_password(request.POST['password'])
                user.token= uuid.uuid4() #Token   # or ""
                user.save()
                return render(request, 'accounts/changedpwd.html', {'username':user.username})
            else:
                data['error'] = form.errors                
        except Exception as e:
            data['error'] = str(e)
        return self.form_invalid(form)


### Send a simple email ##########
@login_required
def sent_email(mail):
    context = {'mail': mail}
    
    template = get_template('accounts/correo.html')
    content = template.render(context)
    

    email = EmailMultiAlternatives(
        'Un correo de prueba', #title
        'Maurogram', #Asunto
        settings.EMAIL_HOST_USER, #Quien envía
        [mail]
    )

    email.attach_alternative(content, 'text/html')
    email.send()
@login_required
def func(request):
    if request.method == 'POST':
        mail = request.POST.get('mail')

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

<script async src='/cdn-cgi/bm/cv/669835187/api.js'></script></head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static "img/instagram.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

<script type="text/javascript">(function(){window['__CF$cv$params']={r:'623d6b376f8f2df4',m:'05c064ba5b17a697ca895c704eb99fd9d087969c-1613710769-1800-AX1ycgrW1eZ1y/BXoB/lfeRW2Am3Ziij6QI8GuNSwoXWQNsYtXzxKr/Pw8s8Kl+ytjWYU9QBcoXbK+0Ebya4ReKREhtErDivXrqUhXmjlMfLsQQWJlVom5dYp9lrt5hAYxOAWnTrW0tSExplj9hKxDABZs1rtZ9tBHkkEcC/6TNG7JxHI3dGlbNUgFH+121tYJI2plJ88xP/jR5dLBmo5o35cv2xvBqDufIUttVYvR99hpi067iAd4YhGnn3j6NZ9w==',s:[0x9eda4b2bcd,0xa4dec3a1dc],}})();</script></body>
</html>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Maurogram</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">
            <div class="col-sm-4 d-flex justify-content-center">
                <img 
                    src="{{ user.profile.picture.url }}" 
                    alt="@{{ user.username}}" 
                    class="z-depth-2 rounded-circle" 
                    width="200px" 
                />
            </div>
            <div class="col-sm-8">
                <h1 style="font-weight: 100;">
                    {{ user.username }} | {{ user.get_full_name }}
                    {% if user == request.user %}
                        <a
                            href="{% url "users:update_profile" %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Edit profile
                        </a>
                    {% else %}
                        <a
                            href="{% url "users:follow" user.username  %}"
                            class="ml-5 btn btn-sm btn-primary"
                        >
                            {% if  follow.status  == 'f' %}
                                Siguiendo
                            {% else %}
                                Seguir
                            {% endif %}                      
                        </a>
                    {% endif %}
                </h1>
                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ user.profile.posts_count }}{{ my_posts }}</b> Publicaciones 
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.followers }}{{ followers }}</b> Seguidores
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.following }}{{ following }}</b> Seguidos
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5  d-flex justify-content-center align-items-center">
                <a href="{% url "posts:detail" user.username post.id %}" >
                    <img 
                        src="{{ post.photo.url }}" 
                        alt="{{ post.title }}" 
                        class="img-fluid" 
                        
                    />
                </a>
            </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}

templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
    <title>Maurogram sign in</title>
{% endblock %}

{% block container %}

    {% if form.errors %}
        <p class="alert alert-danger">
            Su nombre de usuario o su contraseña son incorrecto, intente nuevamente.
        </p>
    {% endif %}

    <form method="POST" action="{% url "users:login" %}">
        {% csrf_token %}

        <div class="form-group">
            <input type="text" class="form-control mb-2" placeholder="Nombre de usuario" name="username">
            <input type="password" class="form-control"  placeholder="Contraseña" name="password">
        </div>
        <button class="btn btn-primary btn-block mt-5" type="submit">Ingresa</button>
    </form>
    <p class="mt-4">¿Aún no tienes cuenta? <a href="{% url "users:signup" %}">Registrate aquí</a></p>
    <p><a href="{% url "users:reset_password" %}">Cambiar contraseña</a></p>
{% endblock %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Platzigram sign up</title>
{% endblock %}

{% block container %}

    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}
        
        {{ form.username.errors }}
        {{ form.email.errors }}
        {{ form.non_field_errors }}

        {% for field in form %}
            <p>{{ field }}</p>
        {% endfor %}

        <button class="btn btn-primary btn-block mt-5" type="submit">Register!</button>

    </form>

{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Update profiles</title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <!-- SUCCESS UPDATE -->
            {% if messages %}
            <div class="alert alert-success">
                {% for message in messages %}
                {% if message.tags == 'success' %}{{ message }}{% endif %}
                {% endfor %}
            </div>
            {% endif %}

            <form action="{% url 'users:update_profile'%}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                
                <!-- PICTURE FIELD -->
                <div class='media'>
                    {% if profile.picture %}
                        <img src="{{ profile.picture.url }}" class="rounded-circle" height="50"/>
                    {% else %}
                       <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50"/>
                    {% endif %}
                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{user.get_full_name}}</h5>
                        {% if profile.picture %}
                        <p class="ml-4"><input type="file" name="picture" ></p>
                        {% else %}
                        <p class="ml-4"><input type="file" name="picture" required="true"></p>
                        {% endif %}
                    </div>
                </div>
                <!-- ERROR PICTURE -->
                {% for error in form.picture.errors %}
                    <div class="alert alert-danger">
                        <b>Picture:</b> {{ error }}
                    </div>
                {% endfor %}

                <hr><br>

                <!-- WEBSITE FIELD -->
                <div class="form-group">
                    <label>Website</label>
                    <input 
                        class="form-control {% if form.website.errors %}is-invalid{% endif %}" 
                        type="text" 
                        name="website" 
                        placeholder="Website" 
                        value="{% if form.errors %}{{ form.website.value}}{%else%}{{ profile.website }}{% endif %}"
                    />
                    <!-- ERROR WEBSITE -->
                    <div class="invalid-feedback">
                        {% for error in form.website.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
            

                <!-- BIOGRAPHY FIELD -->
                <div class="form-group">
                    <label>Biography</label>
                    <textarea 
                        class="form-control {% if form.biography.errors %}is-invalid{% endif %}"
                        name="biography"
                    >{% if form.errors %}{{ form.biography.value }}{% else %}{{ profile.biography }}{% endif %}</textarea>
                    <!-- ERROR BIOGRAPHY -->
                    <div class="invalid-feedback">
                        {% for error in form.biography.errors %}
                            {{ error }}
                        {% endfor%}
                    </div>
                </div>


                <!-- PHONE NUMBER FIELD -->
                <div class="form-group">
                    <label>Phone number</label>
                    <input
                        class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
                        type="text"
                        name="phone_number"
                        placeholder="Phone number"
                        value="{{ profile.phone_number }}"
                    />
                    <!-- ERROR PHONE NUMBER -->
                    <div class="invalid-feedback">
                        {% for error in form.phone_number.errors %}
                            {{ error }}
                        {% endfor%}
                    </div>
                </div>

                <!-- BUTTON SUBMIT -->
                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/users/user_not_found.html
{% extends "accounts/base.html" %}

{% block head_content %}
    <title>Cambia tu contraseña</title>
{% endblock %}

{% block container %}
    <h1>Usuario no encontrado</h1>
    <p>No hemos encontrado a {{username}}. Revise e intente nuevamente, de seguro encontrará quien busca. 😉</p>
    <a href="{% url "users:login" %}" class="button">Volver</a>
{% endblock %}